  export const ACTION_TYPES = {
    GET_CITY: `GET_CITY`,
    GET_CITY_SUCCESS: 'GET_CITY_SUCCESS',
    GET_CITY_FAILED: 'GET_CITY_FAILED',

    GET_DISTRICT: `GET_DISTRICT`,
    GET_DISTRICT_SUCCESS: 'GET_DISTRICT_SUCCESS',
    GET_DISTRICT_FAILED: 'GET_DISTRICT_FAILED',

    GET_WARD: `GET_WARD`,
    GET_WARD_SUCCESS: 'GET_WARD_SUCCESS',
    GET_WARD_FAILED: 'GET_WARD_FAILED',
  }
  